name: Unit Tests
on:
  push:
    branches: 
      - main
  pull_request:

jobs:
  build-and-cache:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      NPM_CONFIG_UNSAFE_PERM: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install
        run: npm ci
      - name: Build
        run: npm run compile
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: tests-build-cache-${{ github.run_number }}
          path: node_modules/.cache/nx
          retention-days: 1

  unit-test:
    needs: build-and-cache
    strategy:
      fail-fast: false
      matrix:
        node: ["18", "20", "22"]
        include:
            - node: 20
              code-coverage: true
    runs-on: ubuntu-latest
    env:
      NPM_CONFIG_UNSAFE_PERM: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install
        run: npm ci
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: tests-build-cache-${{ github.run_number }}
          path: node_modules/.cache/nx
      - name: Build
        run: npm run compile
      - name: Unit tests (Full)
        run: npm run test

